import { Injectable } from '@angular/core';
import { pickRandom } from '../utilities/dice.definitions';

@Injectable({
  providedIn: 'root',
})
export class NameService {
  private heroNames = [
    "Galahad",
    "Anharn",
    "Belorion",
    "Edrath",
    "Hercules",
    "Thalric",
    "Valerius",
    "Kaelen",
    "Isolde",
    "Zephyra",
    "Caspian",
    "Elowen",
    "Garrick",
    "Brynne",
    "Aurelius",
    "Morgath",
    "Lyra",
    "Draven",
    "Sylas",
    "Rowan",
    "Althea",
    "Kestrel",
    "Sigurd",
    "Beowulf",
    "Haldor",
    "Fenris",
    "Vespera",
    "Torin",
    "Xanthe",
    "Leandros",
    "Seraphina",
    "Caelum",
    "Icarus",
    "Elara",
    "Roderick",
    "Cormac",
    "Finnian",
    "Soren",
    "Tamsin",
    "Varick",
    "Ignatius",
    "Octavia",
    "Hadrian",
    "Lucius",
    "Cassian",
    "Thalia",
    "Evander",
    "Perseus",
    "Orion",
    "Atlas",
    "Calliope",
    "Lysander",
    "Eamon",
    "Kaelith",
    "Balthazar",
    "Sterling",
    "Arcturus",
    "Valen",
    "Runa",
    "Eirik",
    "Theon",
    "Alistair",
    "Vance",
    "Jaxon",
    "Kael",
    "Nyx",
    "Solara",
    "Titus",
    "Kira",
    "Saber",
  ];

  private enemyNames = [
    "Gorgos",
    "Malphas",
    "Xyloth",
    "Vrak",
    "Skinner",
    "Bone-Cruncher",
    "Night-Stalker",
    "Blood-Feast",
    "Ulgoth",
    "Draznax",
    "Krix",
    "Void-Wraith",
    "Gloom-Stalker",
    "Shadow-Reaper",
    "Abyssal-Maw",
    "Cinder-Husk",
    "Rot-Walker",
    "Blight-Crawler",
    "Flesh-Stitcher",
    "Skitter-Kin",
    "Marrow-Driller",
    "Soul-Eater",
    "Grim-Tongue",
    "Ichor-Swell",
    "Pox-Bringer",
    "Grave-Bound",
    "Sorrow-Knight",
    "Iron-Gnasher",
    "Fang-Lord",
    "Scalp-Hunter",
    "Kruel",
    "Vile-Eye",
    "Death-Knell",
    "Ruin-Walker",
    "Bane-Guard",
    "Hell-Hog",
    "Slime-Brute",
    "Twist-Limb",
    "Murk-Fiend",
    "Spider-Queen",
    "Web-Weaver",
    "Venom-Spit",
    "Gore-Horn",
    "Thrax",
    "Mordrin",
    "Silas the Wicked",
    "Kaelen the Betrayer",
    "Varoth the Cruel",
    "Elara the Damned",
    "Balthazar the Black",
    "Vane",
    "The Collector",
    "The Puppet Master",
    "The Nameless",
    "The Hollow",
    "Obsidian",
    "Iron-Claw",
    "Frost-Bite",
    "Ash-Walker",
    "Thunder-Hoof",
    "Storm-Caller",
    "Magma-Crag",
    "Stone-Crusher",
    "Dread-Wing",
    "Acid-Tongue",
    "Slaughter-Beast",
    "Troll-King",
    "Goblin-Chief",
    "Orc-Warlord",
    "Chaos-Priest",
  ];

  public getHeroName(): string {
    return pickRandom(this.heroNames);
  }

  public getEnemyName(): string {
    return pickRandom(this.enemyNames);
  }
}
